#pragma once

#include "Shape.h"
#include "Rect3.h"
#include "Line3.h"
#include "Plane3.h"
#include "Triangle3.h"
#include "Capsule3.h"
#include "Box3.h"
#include "Sphere3.h"
#include "Frustum3.h"
#include "CollMap.h"
#include "KdtTriangleMesh.h"
#include "HeightField.h"
#include "CompoundShape.h"
#include "Parabola3.h"
//#include "BvhTriangle3Mesh.h"